# 複数のDockerコンテナが一緒に動作するアプリケーションの設定を定義する。
# アプリが使用する各サービス（データベース、キャッシュ、APIサーバーなど）を定義し、
# それらのサービス間のリンクやネットワーク、ボリュームなどを指定する。
# `docker-compose up` コマンドで使用され、一連のサービスを起動する。

# https://docs.docker.com/compose/compose-file/
# https://github.com/compose-spec/compose-spec

services:
  # appという名前でホットリロード開発環境のコンテナを起動する
  app:
    # NOTE: すべて小文字で記号は使えない
    image: gotodo
    build:
      # NOTE: Dockerfileのあるディレクトリを指定する。本来デフォルト値なので不要だが、
      # Docker Compose version v2.19.0では指定しないとエラーになる。
      context: .
      # args:
        # ↓DockerfileのARGを指定していそうだが、現状ARGを使っていないので不要？
        # - target=dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      # ホスト側のポート:コンテナ側のポート、という形式でマッピングしている。
      - "18000:8080"
