# 複数のDockerコンテナが一緒に動作するアプリケーションの設定を定義する。
# アプリが使用する各サービス（データベース、キャッシュ、APIサーバーなど）を定義し、
# それらのサービス間のリンクやネットワーク、ボリュームなどを指定する。
# `docker-compose up` コマンドで使用され、一連のサービスを起動する。

# https://docs.docker.com/compose/compose-file/
# https://github.com/compose-spec/compose-spec

version: '3.9'
services:
  # appという名前でホットリロード開発環境のコンテナを起動する
  app:
    image: go_todo_app
    build:
      context: .
      args:
        - target=dev
    volumes:
      - .:/app
    ports:
      - "18080:80"
#   db:
#     image: postgres:15
#     container_name: postgres
#     ports:
#       - 5432:5432
#     volumes:
#       - db-store:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: test
#       POSTGRES_PASSWORD: test
#       POSTGRES_DB: test
# volumes:
#   db-store: